// Business writes are authorized and persisted by the server, never by browser storage.
async function api(url, data) {
 const r=await fetch(url,{method:data===undefined?'GET':'POST',credentials:'same-origin',headers:data===undefined?{}:{'Content-Type':'application/json'},body:data===undefined?undefined:JSON.stringify(data)});
 const result=await r.json();if(!r.ok){const error=new Error(result.error||'请求失败');error.status=r.status;throw error;}return result;
}
function clearState(){session=null;role='client';scenes=[];applications=[];tasks=[];inquiries=[];accounts=[];renderAll();}
async function refreshState(){const s=await api('/api/state');session={accountId:s.me.id};role=roleFromAccount(s.me);scenes=s.scenes;applications=s.applications;tasks=s.tasks;inquiries=s.inquiries;accounts=s.accounts;renderAll();}
async function perform(name,data,options={}){try{const r=await api('/api/action',{action:name,data});if(options.close)closeModal();await refreshState();if(options.tab){const buttons=document.querySelectorAll('.tabs button');const ix=options.tab==='accounts'?3:1;showInternalTab(options.tab,buttons[ix]);}return r;}catch(e){if(e.status===401){clearState();openLogin();}alert(e.message);return null;}}
save=()=>{};
setRole=()=>{if(session)refreshState().catch(e=>alert(e.message));};
openLogin=function(){document.getElementById('modalContent').innerHTML=`<div class="kicker" style="color:var(--green)">Fieldbook sign in</div><h2>登录场景库</h2><p class="muted">使用管理员为您开通的账号登录。</p><form class="form" onsubmit="login(event)"><div class="field"><label>登录邮箱</label><input name="email" type="email" autocomplete="username" required></div><div class="field" style="margin-top:12px"><label>密码</label><input name="password" type="password" autocomplete="current-password" required></div><div id="loginError" role="alert" class="help" style="color:#a23d3b"></div><button class="primary" style="margin-top:10px">登录</button></form>`;document.getElementById('modal').classList.add('open');};
login=async function(e){e.preventDefault();const f=e.target,b=f.querySelector('button');b.disabled=true;try{await api('/api/login',{email:f.elements.email.value,password:f.elements.password.value});await refreshState();closeModal();switchView(role==='client'?'library':'workbench');}catch(err){document.getElementById('loginError').textContent=err.message;}finally{b.disabled=false;}};
logout=async function(){try{await api('/api/logout',{});clearState();switchView('library');openLogin();}catch(e){alert(e.message);}};
bootstrap=async function(){clearState();try{await refreshState();}catch(e){if(e.status===401)openLogin();else{document.getElementById('sceneGrid').innerHTML='<div class="empty">无法连接服务：'+esc(e.message)+'。请刷新重试。</div>';}}};
submitInquiry=async function(id){const contact=document.getElementById('inquiryContact').value.trim();if(!contact)return alert('请留下联系方式');if(await perform('inquiry',{sceneId:id,contact},{close:true}))alert('需求已登记');};
const originalAccountForm=openAccountForm;
openAccountForm=function(id){originalAccountForm(id);const form=document.querySelector('#modalContent form');form.querySelector('.help').textContent='权限由服务端角色决定。';form.querySelector('#accountScope').readOnly=true;const field=document.createElement('div');field.className='field full';field.innerHTML=`<label>${id?'设置新密码（留空则不修改）':'初始密码 *'}</label><input name="password" type="password" autocomplete="new-password" minlength="12" maxlength="128" ${id?'':'required'}><small class="help">至少12位，请通过安全渠道交给账号使用者。</small>`;form.querySelector('.form-grid').append(field);};
saveAccount=async function(e,id){e.preventDefault();const f=e.target.elements,data={id,name:f.name.value,email:f.email.value,role:f.role.value,org:f.org.value,password:f.password.value};if(await perform('account',data,{close:true,tab:'accounts'}))alert('账号已保存');};
toggleAccount=async id=>perform('toggleAccount',{id},{tab:'accounts'});
const originalApplyForm=openApplyForm;
openApplyForm=function(id){originalApplyForm();const f=document.querySelector('#modalContent form');const previous=id&&applications.find(x=>x.id===id);f._previous=previous;if(previous){for(const k of ['name','industry','place','period','task','data','contact','note'])f.elements[k].value=previous[k]||'';document.getElementById('applyPhotos').required=false;document.getElementById('applyPhotoNames').textContent=`已保存${previous.photos.length}张图片，选新文件将替换原图片。`;document.getElementById('applyVideoNames').textContent=`已保存${previous.videos.length}段视频，选新文件将替换原视频。`;}const helps=f.querySelectorAll('.help');helps[0].textContent='JPG / PNG / WebP，每张最多20MB，最多20张。';helps[1].textContent='MP4 / WebM / MOV，每段最多500MB，最多20段。建议使用H.264编码的MP4以便在线播放。';const status=document.createElement('div');status.id='uploadStatus';status.className='notice';status.style.marginTop='16px';status.textContent='素材会上传并保存在服务器，提交后进入审核。';f.append(status);};
function uploadFile(file,onProgress){return new Promise((resolve,reject)=>{const x=new XMLHttpRequest();x.open('POST','/api/upload?name='+encodeURIComponent(file.name));const type=file.type||({jpg:'image/jpeg',jpeg:'image/jpeg',png:'image/png',webp:'image/webp',mp4:'video/mp4',webm:'video/webm',mov:'video/quicktime'}[file.name.split('.').pop().toLowerCase()]);x.setRequestHeader('Content-Type',type||'application/octet-stream');x.upload.onprogress=e=>{if(e.lengthComputable)onProgress(Math.round(e.loaded/e.total*100));};x.onload=()=>{let r;try{r=JSON.parse(x.responseText);}catch{return reject(new Error('上传服务返回异常，请重试'));}if(x.status<200||x.status>=300)return reject(new Error(r.error||'上传失败'));resolve(r.url);};x.onerror=()=>reject(new Error('网络连接中断，请重试上传'));x.timeout=30*60*1000;x.ontimeout=()=>reject(new Error('上传超时，请重试'));x.send(file);});}
submitApplication=async function(e){
 e.preventDefault();const form=e.target,f=form.elements,photos=[...document.getElementById('applyPhotos').files],videos=[...document.getElementById('applyVideos').files],status=document.getElementById('uploadStatus'),button=form.querySelector('button');
 if((!photos.length&&!form._previous?.photos.length)||photos.length>20||videos.length>20)return alert('至少1张图片，每类素材最多20个');if(photos.some(x=>x.size>20*1024*1024)||videos.some(x=>x.size>500*1024*1024))return alert('图片最大20MB，视频最大500MB');
 const data={};for(const k of ['name','industry','place','period','task','data','contact','note'])data[k]=f[k].value;
 const close=document.querySelector('.dialog>.close');button.disabled=true;close.disabled=true;try{
  const uploaded={photos:photos.length?[]:(form._previous?.photos||[]),videos:videos.length?[]:(form._previous?.videos||[])};if(form._previous)data.id=form._previous.id;let n=0;for(const [kind,files]of [['photos',photos],['videos',videos]])for(const file of files){n++;let url=file._serverUrl;if(!url){url=await uploadFile(file,p=>status.textContent=`上传 ${n}/${photos.length+videos.length}：${file.name} · ${p}%`);file._serverUrl=url;}uploaded[kind].push(url);}
  status.textContent='素材上传完成，正在提交申报…';await api('/api/action',{action:'apply',data:{...data,...uploaded}});closeModal();await refreshState();switchView('workbench');showSupplierTab('mine',document.querySelector('.tabs button:nth-child(2)'));alert('申报已保存到服务器，等待审核。');
 }catch(err){status.textContent='提交未完成：'+err.message+'。已上传的文件会在本次重试时复用。';}finally{button.disabled=false;close.disabled=false;}
};
reviewApplication=async function(id,decision){let note='';if(decision==='reject'){note=prompt('填写退回原因');if(note===null)return;}if(await perform('review',{id,decision,note},{tab:'audit'}))alert(decision==='approve'?'已审核通过，客户场景库已可查看图片和视频。':'已退回并记录原因。');};
const originalAppDetail=appDetail;
appDetail=function(id){originalAppDetail(id);const a=applications.find(x=>x.id===id);if(a.reviewNote)document.getElementById('modalContent').insertAdjacentHTML('beforeend',`<div class="notice">审核意见：${esc(a.reviewNote)}</div>`);};
openTaskForm=async function(){try{const suppliers=await api('/api/suppliers');if(!scenes.length)return alert('请先审核通过至少一个场景');document.getElementById('modalContent').innerHTML=`<h2>创建并下发采集任务</h2><form class="form" onsubmit="createTask(event)"><div class="form-grid"><div class="field"><label>关联场景 *</label><select name="sceneId">${scenes.map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('')}</select></div><div class="field"><label>计划周期 *</label><input name="date" required></div><div class="field"><label>下发方式</label><select name="mode"><option value="pool">开放供应商领取</option><option value="assigned">直接指派供应商</option></select></div><div class="field"><label>指派供应商</label><select name="supplierId"><option value="">请选择</option>${suppliers.map(x=>`<option value="${x.id}">${esc(x.org)} · ${esc(x.name)}</option>`).join('')}</select></div><div class="field full"><label>内部负责人</label><input name="owner"></div></div><button class="primary" style="margin-top:15px">创建任务</button></form>`;document.getElementById('modal').classList.add('open');}catch(e){alert(e.message);}};
createTask=async function(e){e.preventDefault();const f=e.target.elements,data={};for(const k of ['sceneId','date','mode','supplierId','owner'])data[k]=f[k].value;if(await perform('task',data,{close:true}))alert('任务已下发');};
claimTask=async id=>{if(await perform('claim',{id}))alert('已领取任务');};
supplierStart=async id=>perform('start',{id});
advanceTask=async id=>perform('advance',{id});
supplierHTML=function(){const available=tasks.filter(t=>t.stage==='待领取'),claimed=tasks.filter(t=>t.supplierId===session?.accountId);return `<div class="section-head"><h1>供应商工作台</h1><button class="primary" onclick="openApplyForm()">+ 申报新场景</button></div><div class="tabs"><button class="active" onclick="showSupplierTab('tasks',this)">可领取任务 ${available.length}</button><button onclick="showSupplierTab('mine',this)">我的申报 ${applications.length}</button><button onclick="showSupplierTab('claimed',this)">我的执行任务 ${claimed.length}</button></div><div id="supplierPanel">${supplierTaskPanel()}</div>`;};
supplierClaimedPanel=function(){const list=tasks.filter(t=>t.supplierId===session?.accountId);return list.length?`<table class="table"><thead><tr><th>任务</th><th>计划</th><th>状态</th><th>操作</th></tr></thead><tbody>${list.map(t=>`<tr><td>${esc(t.name)}</td><td>${esc(t.date)}</td><td>${esc(t.stage)}</td><td>${t.stage==='已排期'?`<button class="small-btn" onclick="supplierStart('${t.id}')">开始执行</button>`:''}<button class="small-btn" onclick="taskDetail('${t.id}')">详情</button></td></tr>`).join('')}</tbody></table>`:'<div class="empty">尚未领取或获指派任务。</div>';};
supplierMinePanel=function(){return applications.length?`<table class="table"><thead><tr><th>场景</th><th>素材</th><th>审核状态</th><th>操作</th></tr></thead><tbody>${applications.map(a=>`<tr><td>${esc(a.name)}<br><small>${esc(a.place)}</small></td><td>${a.photos.length}图 / ${a.videos.length}视频</td><td>${esc(a.status)}<br><small>${esc(a.reviewNote||'')}</small></td><td><button class="small-btn" onclick="appDetail('${a.id}')">查看</button>${a.status==='已退回'?` <button class="small-btn" onclick="openApplyForm('${a.id}')">修改重提</button>`:''}</td></tr>`).join('')}</tbody></table>`:'<div class="empty">尚未申报场景。</div>';};
const originalRenderAll=renderAll;
renderAll=function(){originalRenderAll();const me=accounts.find(x=>x.id===session?.accountId);document.querySelector('.logout').textContent=me?'退出登录':'登录';document.querySelector('.logout').onclick=me?logout:openLogin;if(role==='internal'&&me?.role!=='平台管理员'){const tab=document.querySelector('.tabs button:nth-child(4)');if(tab)tab.style.display='none';}document.querySelectorAll('.gallery video').forEach(v=>v.preload='metadata');};
document.addEventListener('visibilitychange',()=>{if(!document.hidden&&session&&!document.getElementById('modal').classList.contains('open'))refreshState().catch(e=>{if(e.status===401){clearState();openLogin();}});});
bootstrap();
