// Business writes are authorized and persisted by the server, never by browser storage.
let archivedScenes=[], internalTab='plan', sceneListFilter='current';
function isPlatformAdmin(){return accounts.find(a=>a.id===session?.accountId)?.role==='平台管理员';}
async function api(url, data) {
 const r=await fetch(url,{method:data===undefined?'GET':'POST',credentials:'same-origin',headers:data===undefined?{}:{'Content-Type':'application/json'},body:data===undefined?undefined:JSON.stringify(data)});
 const result=await r.json();if(!r.ok){const error=new Error(result.error||'请求失败');error.status=r.status;throw error;}return result;
}
function clearState(){session=null;role='client';scenes=[];archivedScenes=[];internalTab='plan';applications=[];tasks=[];inquiries=[];accounts=[];renderAll();}
async function refreshState(){const s=await api('/api/state');session={accountId:s.me.id};role=roleFromAccount(s.me);scenes=s.scenes;archivedScenes=s.archivedScenes||[];applications=s.applications;tasks=s.tasks;inquiries=s.inquiries;accounts=s.accounts;renderAll();}
async function perform(name,data,options={}){try{const r=await api('/api/action',{action:name,data});if(options.close)closeModal();await refreshState();if(options.tab){const buttons=document.querySelectorAll('.tabs button');const ix={accounts:3,scenes:4,audit:1}[options.tab]??1;showInternalTab(options.tab,buttons[ix]);}return r;}catch(e){if(e.status===401){clearState();openLogin();}else if(e.status===409)await refreshState().catch(()=>{});alert(e.message);return null;}}
save=()=>{};
setRole=()=>{if(session)refreshState().catch(e=>alert(e.message));};
openLogin=function(){document.getElementById('modalContent').innerHTML=`<div class="kicker" style="color:var(--green)">Fieldbook sign in</div><h2>登录场景库</h2><p class="muted">使用管理员为您开通的账号登录。</p><form class="form" onsubmit="login(event)"><div class="field"><label>登录邮箱</label><input name="email" type="email" autocomplete="username" required></div><div class="field" style="margin-top:12px"><label>密码</label><input name="password" type="password" autocomplete="current-password" required></div><div id="loginError" role="alert" class="help" style="color:#a23d3b"></div><button class="primary" style="margin-top:10px">登录</button></form>`;document.getElementById('modal').classList.add('open');};
login=async function(e){e.preventDefault();const f=e.target,b=f.querySelector('button');b.disabled=true;try{await api('/api/login',{email:f.elements.email.value,password:f.elements.password.value});await refreshState();closeModal();switchView(role==='client'?'library':'workbench');}catch(err){document.getElementById('loginError').textContent=err.message;}finally{b.disabled=false;}};
logout=async function(){try{await api('/api/logout',{});clearState();switchView('library');openLogin();}catch(e){alert(e.message);}};
bootstrap=async function(){clearState();try{await refreshState();}catch(e){if(e.status===401)openLogin();else{document.getElementById('sceneGrid').innerHTML='<div class="empty">无法连接服务：'+esc(e.message)+'。请刷新重试。</div>';}}};
submitInquiry=async function(id){const contact=document.getElementById('inquiryContact').value.trim();if(!contact)return alert('请留下联系方式');if(await perform('inquiry',{sceneId:id,contact},{close:true}))alert('需求已登记');};
const originalAccountForm=openAccountForm;
openAccountForm=function(id){originalAccountForm(id);const form=document.querySelector('#modalContent form');form.querySelector('.help').textContent='权限由服务端角色决定。';form.querySelector('#accountScope').readOnly=true;const field=document.createElement('div');field.className='field full';field.innerHTML=`<label>${id?'设置新密码（留空则不修改）':'初始密码 *'}</label><input name="password" type="password" autocomplete="new-password" minlength="12" maxlength="128" ${id?'':'required'}><small class="help">至少12位，请通过安全渠道交给账号使用者。</small>`;form.querySelector('.form-grid').append(field);};
saveAccount=async function(e,id){e.preventDefault();const f=e.target.elements,data={id,name:f.name.value,email:f.email.value,role:f.role.value,org:f.org.value,password:f.password.value};if(await perform('account',data,{close:true,tab:'accounts'}))alert('账号已保存');};
toggleAccount=async id=>perform('toggleAccount',{id},{tab:'accounts'});
const originalApplyForm=openApplyForm;
openApplyForm=function(id){originalApplyForm();const f=document.querySelector('#modalContent form');const previous=id&&applications.find(x=>x.id===id);f._previous=previous;if(previous){for(const k of ['name','industry','place','period','task','data','contact','note'])f.elements[k].value=previous[k]||'';document.getElementById('applyPhotos').required=false;document.getElementById('applyPhotoNames').textContent=`已保存${previous.photos.length}张图片，选新文件将替换原图片。`;document.getElementById('applyVideoNames').textContent=`已保存${previous.videos.length}段视频，选新文件将替换原视频。`;}const helps=f.querySelectorAll('.help');helps[0].textContent='JPG / PNG / WebP，每张最多20MB，最多20张。';helps[1].textContent='MP4 / WebM / MOV，每段最多500MB，最多20段。建议使用H.264编码的MP4以便在线播放。';const status=document.createElement('div');status.id='uploadStatus';status.className='notice';status.style.marginTop='16px';status.textContent='素材会上传并保存在服务器，提交后进入审核。';f.append(status);};
function uploadFile(file,onProgress){return new Promise((resolve,reject)=>{const x=new XMLHttpRequest();x.open('POST','/api/upload?name='+encodeURIComponent(file.name));const type=file.type||({jpg:'image/jpeg',jpeg:'image/jpeg',png:'image/png',webp:'image/webp',mp4:'video/mp4',webm:'video/webm',mov:'video/quicktime'}[file.name.split('.').pop().toLowerCase()]);x.setRequestHeader('Content-Type',type||'application/octet-stream');x.upload.onprogress=e=>{if(e.lengthComputable)onProgress(Math.round(e.loaded/e.total*100));};x.onload=()=>{let r;try{r=JSON.parse(x.responseText);}catch{return reject(new Error('上传服务返回异常，请重试'));}if(x.status<200||x.status>=300)return reject(new Error(r.error||'上传失败'));resolve(r.url);};x.onerror=()=>reject(new Error('网络连接中断，请重试上传'));x.timeout=30*60*1000;x.ontimeout=()=>reject(new Error('上传超时，请重试'));x.send(file);});}
submitApplication=async function(e){
 e.preventDefault();const form=e.target,f=form.elements,photos=[...document.getElementById('applyPhotos').files],videos=[...document.getElementById('applyVideos').files],status=document.getElementById('uploadStatus'),button=form.querySelector('button');
 if((!photos.length&&!form._previous?.photos.length)||photos.length>20||videos.length>20)return alert('至少1张图片，每类素材最多20个');if(photos.some(x=>x.size>20*1024*1024)||videos.some(x=>x.size>500*1024*1024))return alert('图片最大20MB，视频最大500MB');
 const data={};for(const k of ['name','industry','place','period','task','data','contact','note'])data[k]=f[k].value;
 const close=document.querySelector('.dialog>.close');button.disabled=true;close.disabled=true;try{
  const uploaded={photos:photos.length?[]:(form._previous?.photos||[]),videos:videos.length?[]:(form._previous?.videos||[])};if(form._previous)data.id=form._previous.id;let n=0;for(const [kind,files]of [['photos',photos],['videos',videos]])for(const file of files){n++;let url=file._serverUrl;if(!url){url=await uploadFile(file,p=>status.textContent=`上传 ${n}/${photos.length+videos.length}：${file.name} · ${p}%`);file._serverUrl=url;}uploaded[kind].push(url);}
  status.textContent='素材上传完成，正在提交申报…';await api('/api/action',{action:'apply',data:{...data,...uploaded}});closeModal();await refreshState();switchView('workbench');showSupplierTab('mine',document.querySelector('.tabs button:nth-child(2)'));alert('申报已保存到服务器，等待审核。');
 }catch(err){status.textContent='提交未完成：'+err.message+'。已上传的文件会在本次重试时复用。';}finally{button.disabled=false;close.disabled=false;}
};
reviewApplication=async function(id,decision){let note='';if(decision==='reject'){note=prompt('填写退回原因');if(note===null)return;}if(await perform('review',{id,decision,note},{tab:'audit'}))alert(decision==='approve'?'已审核通过，客户场景库已可查看图片和视频。':'已退回并记录原因。');};
const originalAppDetail=appDetail;
appDetail=function(id){originalAppDetail(id);const a=applications.find(x=>x.id===id);if(a.reviewNote)document.getElementById('modalContent').insertAdjacentHTML('beforeend',`<div class="notice">审核意见：${esc(a.reviewNote)}</div>`);};
openTaskForm=async function(){try{const suppliers=await api('/api/suppliers');if(!scenes.length)return alert('请先审核通过至少一个场景');document.getElementById('modalContent').innerHTML=`<h2>创建并下发采集任务</h2><form class="form" onsubmit="createTask(event)"><div class="form-grid"><div class="field"><label>关联场景 *</label><select name="sceneId">${scenes.map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('')}</select></div><div class="field"><label>计划周期 *</label><input name="date" required></div><div class="field"><label>下发方式</label><select name="mode"><option value="pool">开放供应商领取</option><option value="assigned">直接指派供应商</option></select></div><div class="field"><label>指派供应商</label><select name="supplierId"><option value="">请选择</option>${suppliers.map(x=>`<option value="${x.id}">${esc(x.org)} · ${esc(x.name)}</option>`).join('')}</select></div><div class="field full"><label>内部负责人</label><input name="owner"></div></div><button class="primary" style="margin-top:15px">创建任务</button></form>`;document.getElementById('modal').classList.add('open');}catch(e){alert(e.message);}};
createTask=async function(e){e.preventDefault();const f=e.target.elements,data={};for(const k of ['sceneId','date','mode','supplierId','owner'])data[k]=f[k].value;if(await perform('task',data,{close:true}))alert('任务已下发');};
claimTask=async id=>{if(await perform('claim',{id}))alert('已领取任务');};
supplierStart=async id=>perform('start',{id});
advanceTask=async id=>perform('advance',{id});
supplierHTML=function(){const available=tasks.filter(t=>t.stage==='待领取'),claimed=tasks.filter(t=>t.supplierId===session?.accountId);return `<div class="section-head"><h1>供应商工作台</h1><button class="primary" onclick="openApplyForm()">+ 申报新场景</button></div><div class="tabs"><button class="active" onclick="showSupplierTab('tasks',this)">可领取任务 ${available.length}</button><button onclick="showSupplierTab('mine',this)">我的申报 ${applications.length}</button><button onclick="showSupplierTab('claimed',this)">我的执行任务 ${claimed.length}</button></div><div id="supplierPanel">${supplierTaskPanel()}</div>`;};
supplierClaimedPanel=function(){const list=tasks.filter(t=>t.supplierId===session?.accountId);return list.length?`<table class="table"><thead><tr><th>任务</th><th>计划</th><th>状态</th><th>操作</th></tr></thead><tbody>${list.map(t=>`<tr><td>${esc(t.name)}</td><td>${esc(t.date)}</td><td>${esc(t.stage)}</td><td>${t.stage==='已排期'?`<button class="small-btn" onclick="supplierStart('${t.id}')">开始执行</button>`:''}<button class="small-btn" onclick="taskDetail('${t.id}')">详情</button></td></tr>`).join('')}</tbody></table>`:'<div class="empty">尚未领取或获指派任务。</div>';};
supplierMinePanel=function(){return applications.length?`<table class="table"><thead><tr><th>场景</th><th>素材</th><th>审核状态</th><th>操作</th></tr></thead><tbody>${applications.map(a=>`<tr><td>${esc(a.name)}<br><small>${esc(a.place)}</small></td><td>${a.photos.length}图 / ${a.videos.length}视频</td><td>${esc(a.status)}<br><small>${esc(a.reviewNote||'')}</small></td><td><button class="small-btn" onclick="appDetail('${a.id}')">查看</button>${a.status==='已退回'?` <button class="small-btn" onclick="openApplyForm('${a.id}')">修改重提</button>`:''}</td></tr>`).join('')}</tbody></table>`:'<div class="empty">尚未申报场景。</div>';};
const originalRenderAll=renderAll;
renderAll=function(){originalRenderAll();const me=accounts.find(x=>x.id===session?.accountId);document.querySelector('.logout').textContent=me?'退出登录':'登录';document.querySelector('.logout').onclick=me?logout:openLogin;if(role==='internal'&&me?.role!=='平台管理员'){const tab=document.querySelector('.tabs button:nth-child(4)');if(tab)tab.style.display='none';}if(role==='internal'&&internalTab!=='plan'){const ix={audit:1,inquiries:2,accounts:3,scenes:4}[internalTab];const button=document.querySelectorAll('.tabs button')[ix];if(button&&(internalTab!=='scenes'||isPlatformAdmin())&&(internalTab!=='accounts'||isPlatformAdmin()))showInternalTab(internalTab,button);}document.querySelectorAll('.gallery video').forEach(v=>v.preload='metadata');};

const originalInternalHTML=internalHTML;
internalHTML=function(){const html=originalInternalHTML();return isPlatformAdmin()?html.replace('</div><div id="internalPanel">',`<button data-internal-tab="scenes" onclick="showInternalTab('scenes',this)">场景管理 ${scenes.length}</button></div><div id="internalPanel">`):html;};
const originalInternalTab=showInternalTab;
showInternalTab=function(kind,button){
 if(!button)return;
 if(kind==='scenes'){
  if(!isPlatformAdmin())return;
  internalTab=kind;document.querySelectorAll('.tabs button').forEach(x=>x.classList.remove('active'));button.classList.add('active');document.getElementById('internalPanel').innerHTML=sceneManagementPanel();
 }else{internalTab=kind;originalInternalTab(kind,button);}
};
function sceneLifecycle(s){return s.deletedAt?'已删除':s.enabled===false?'已停用':'已启用';}
function managedScene(id){return [...scenes,...archivedScenes].find(s=>s.id===id);}
function sceneManagementPanel(){
 let list=sceneListFilter==='deleted'?archivedScenes:scenes;
 if(sceneListFilter==='enabled')list=list.filter(s=>s.enabled!==false);
 if(sceneListFilter==='disabled')list=list.filter(s=>s.enabled===false);
 return `<div class="notice">停用或删除后，客户场景库不再展示该场景，也不能通过原素材链接访问。图片、视频及历史任务保留；已领取任务可继续执行。删除的场景可恢复，恢复后默认停用。</div><div class="section-head"><h2>场景管理</h2><select aria-label="场景管理筛选" class="filter" onchange="filterManagedScenes(this.value)">${[['current','全部未删除'],['enabled','已启用'],['disabled','已停用'],['deleted','已删除（可恢复）']].map(([v,n])=>`<option value="${v}" ${sceneListFilter===v?'selected':''}>${n}</option>`).join('')}</select></div>${list.length?`<div style="overflow-x:auto"><table class="table"><thead><tr><th>场景 / 环境</th><th>行业 / 素材</th><th>发布状态</th><th>操作</th></tr></thead><tbody>${list.map(s=>`<tr data-scene-id="${s.id}"><td><b>${esc(s.name)}</b><br><small class="muted">${esc(s.place)}</small></td><td>${esc(s.industry)}<br><small>${(s.photos||[]).length}图 / ${(s.videos||[]).length}视频</small></td><td><span class="pill ${s.deletedAt||s.enabled===false?'rejected':'approved'}">${sceneLifecycle(s)}</span><br><small>${esc(s.status)}</small></td><td>${sceneManagementActions(s)}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">当前筛选下暂无场景。</div>'}`;
}
function sceneManagementActions(s){return `<button class="small-btn" onclick="showManagedScene('${s.id}')">查看</button> ${s.deletedAt?`<button class="small-btn" onclick="restoreScene('${s.id}')">恢复场景</button>`:`<button class="small-btn" onclick="openSceneEdit('${s.id}')">修改详情</button> <button class="small-btn" onclick="toggleScene('${s.id}')">${s.enabled===false?'启用':'停用'}</button> <button class="small-btn" style="color:#a23d3b" onclick="deleteScene('${s.id}')">删除</button>`}`;}
function filterManagedScenes(filter){sceneListFilter=filter;document.getElementById('internalPanel').innerHTML=sceneManagementPanel();}
function showManagedScene(id){
 if(!isPlatformAdmin())return;const s=managedScene(id);if(!s)return alert('场景已更新，请刷新');
 document.getElementById('modalContent').innerHTML=`<div class="kicker">${esc(s.industry)} · ${sceneLifecycle(s)}</div><h2>${esc(s.name)}</h2><p class="muted">${esc(s.desc)}</p><div class="detail-grid">${[['采集环境',s.place],['核心任务',s.task],['数据模态',s.data],['采集周期',s.cycle],['交付规模',s.scale],['采集状态',s.status]].map(([label,v])=>`<div class="detail"><small>${label}</small><b>${esc(v)}</b></div>`).join('')}</div><p>${(s.tags||[]).map(t=>`<span class="pill">${esc(t)}</span>`).join(' ')}</p><div class="gallery">${(s.photos||[]).map(p=>`<img src="${p}" alt="现场图片">`).join('')}${(s.videos||[]).map(v=>`<video controls preload="metadata" src="${v}"></video>`).join('')}</div><div>${sceneManagementActions(s)}</div>`;
 document.getElementById('modal').classList.add('open');
}
const originalShowScene=showScene;
showScene=function(id){if(isPlatformAdmin())showManagedScene(id);else originalShowScene(id);};
const originalRenderLibrary=renderLibrary;
renderLibrary=function(){originalRenderLibrary();if(role!=='internal')return;document.getElementById('readyMetric').textContent=scenes.filter(s=>s.enabled!==false&&s.status==='可立即采集').length;document.querySelectorAll('#sceneGrid .scene').forEach(card=>{const key=/showScene\('([^']+)'\)/.exec(card.getAttribute('onclick')||'')?.[1],s=scenes.find(x=>x.id===key);if(s?.enabled===false)card.querySelector('.scene-body').insertAdjacentHTML('afterbegin','<span class="pill rejected">已停用 · 客户不可见</span>');});};
function openSceneEdit(id){
 if(!isPlatformAdmin())return;const s=managedScene(id);if(!s||s.deletedAt)return alert('该场景已删除，请先恢复');
 const fields=[['name','场景名称',200],['industry','所属行业',100],['place','采集环境',300],['data','数据模态',300],['cycle','采集周期',300],['scale','交付规模',300]];
 document.getElementById('modalContent').innerHTML=`<h2>修改场景详情</h2><form class="form" id="sceneEditForm" onsubmit="saveSceneDetails(event,'${s.id}',${s.revision||0})"><div class="form-grid">${fields.map(([k,label,max])=>`<div class="field"><label>${label} *</label><input name="${k}" value="${esc(s[k])}" maxlength="${max}" required></div>`).join('')}<div class="field full"><label>核心任务 *</label><textarea name="task" rows="3" maxlength="2000" required>${esc(s.task)}</textarea></div><div class="field full"><label>场景介绍 *</label><textarea name="desc" rows="4" maxlength="4000" required>${esc(s.desc)}</textarea></div><div class="field"><label>采集状态</label><select name="status">${['可立即采集','方案评估中'].map(v=>`<option ${s.status===v?'selected':''}>${v}</option>`).join('')}</select></div><div class="field"><label>标签</label><input name="tags" value="${esc((s.tags||[]).join('，'))}"><small class="help">用逗号分隔，最多20个标签，每个不超过60字。</small></div></div><div class="notice" style="margin-top:16px">本次只修改文字详情，保留现有图片、视频及发布状态。</div><div id="sceneEditError" role="alert" style="color:#a23d3b"></div><button class="primary" style="margin-top:10px">保存修改</button></form>`;
 document.getElementById('modal').classList.add('open');
}
async function saveSceneDetails(e,id,revision){
 e.preventDefault();const f=e.target,details={},button=f.querySelector('button');for(const k of ['name','industry','place','data','cycle','scale','task','desc','status'])details[k]=f.elements[k].value.trim();details.tags=f.elements.tags.value.split(/[,，]/).map(x=>x.trim()).filter(Boolean);button.disabled=true;
 try{await api('/api/action',{action:'sceneEdit',data:{id,revision,details}});closeModal();await refreshState();switchView('workbench');showInternalTab('scenes',document.querySelector('[data-internal-tab="scenes"]'));}
 catch(err){f.querySelector('#sceneEditError').textContent=err.message;if(err.status===409)await refreshState().catch(()=>{});if(err.status===401){clearState();openLogin();}}finally{button.disabled=false;}
}
async function toggleScene(id){const s=managedScene(id);if(!isPlatformAdmin()||!s||s.deletedAt)return;if(s.enabled!==false&&!confirm(`停用“${s.name}”？客户将无法查看，相关未领取任务将暂停开放，已有素材与历史记录保留。`))return;await perform('sceneToggle',{id,revision:s.revision||0,enabled:s.enabled===false},{close:true,tab:'scenes'});}
async function deleteScene(id){const s=managedScene(id);if(!isPlatformAdmin()||!s||s.deletedAt)return;if(!confirm(`删除“${s.name}”？场景会从客户场景库移除，图片、视频与历史记录保留，可在“已删除”列表恢复。`))return;await perform('sceneDelete',{id,revision:s.revision||0},{close:true,tab:'scenes'});}
async function restoreScene(id){const s=managedScene(id);if(!isPlatformAdmin()||!s?.deletedAt)return;await perform('sceneRestore',{id,revision:s.revision||0},{close:true,tab:'scenes'});}
const originalTaskForm=openTaskForm;
openTaskForm=async function(){if(!scenes.some(s=>!s.deletedAt&&s.enabled!==false))return alert('暂无已启用场景，请先启用或审核场景');await originalTaskForm();const select=document.querySelector('#modalContent select[name="sceneId"]');if(select)[...select.options].forEach(option=>{const s=scenes.find(x=>x.id===option.value);if(!s||s.deletedAt||s.enabled===false)option.remove();});};
inquiriesPanel=function(){return inquiries.length?`<table class="table"><thead><tr><th>场景</th><th>客户联系方式</th><th>提交日期</th></tr></thead><tbody>${inquiries.map(x=>`<tr><td>${esc(x.sceneName||scenes.find(s=>s.id===x.sceneId)?.name||'已归档场景')}</td><td>${esc(x.contact)}</td><td>${esc(x.date)}</td></tr>`).join('')}</tbody></table>`:'<div class="empty">尚未收到客户询盘。</div>';};
clientHTML=function(){return `<div class="section-head"><h1>客户资料与询盘</h1></div><div class="notice">查看已启用场景的图片、视频与相关资料，提交采集需求。</div><h2>我的询盘</h2>${inquiries.length?`<table class="table"><thead><tr><th>场景</th><th>提交时间</th><th>状态</th></tr></thead><tbody>${inquiries.map(x=>`<tr><td>${esc(x.sceneName||scenes.find(s=>s.id===x.sceneId)?.name||'已归档场景')}</td><td>${esc(x.date)}</td><td>已收到</td></tr>`).join('')}</tbody></table>`:'<div class="empty">尚未提交询盘。</div>'}`;};
document.addEventListener('visibilitychange',()=>{if(!document.hidden&&session&&!document.getElementById('modal').classList.contains('open'))refreshState().catch(e=>{if(e.status===401){clearState();openLogin();}});});
bootstrap();
