/* Same authorized media URLs, no copies or permission bypass. */
(()=>{
 'use strict';
 let active=null;
 const overlay=document.createElement('section');overlay.className='media-viewer';overlay.hidden=true;overlay.setAttribute('role','dialog');overlay.setAttribute('aria-modal','true');overlay.setAttribute('aria-labelledby','mediaTitle');
 overlay.innerHTML=`<header><div><h2 id="mediaTitle"></h2><p id="mediaCount"></p></div><button type="button" data-command="close" aria-label="关闭媒体查看器，返回场景详情">关闭 ×</button></header><div class="media-tools"><button data-command="prev" aria-label="上一个素材">← 上一个</button><button data-command="zoomOut" aria-label="缩小图片">−</button><span id="mediaZoom" aria-live="polite"></span><button data-command="zoomIn" aria-label="放大图片">＋</button><button data-command="fit">适应窗口</button><button data-command="fullscreen">全屏观看</button><button data-command="next" aria-label="下一个素材">下一个 →</button></div><div class="media-stage"><div class="media-surface"></div></div><p class="media-feedback" role="status" aria-live="polite"></p><div class="media-strip" aria-label="选择场景素材"></div><footer>方向键切换 · Esc 返回 · 图片双击放大 / 还原 · 放大后拖动或触摸移动 · 双指缩放</footer>`;
 document.body.append(overlay);
 const stage=overlay.querySelector('.media-stage'),surface=overlay.querySelector('.media-surface'),feedback=overlay.querySelector('.media-feedback'),strip=overlay.querySelector('.media-strip');
 const control=name=>overlay.querySelector(`[data-command="${name}"]`);
 function status(message,retry=false){feedback.textContent=message;if(retry){const button=document.createElement('button');button.type='button';button.textContent='重新加载';button.onclick=()=>render();feedback.append(' ',button);}}
 function stopMedia(){const video=surface.querySelector('video');if(video){const url=video.getAttribute('src');if(url)active?.positions.set(url,video.currentTime||0);video.pause();video.removeAttribute('src');video.load();}}
 function fitSize(){const image=surface.querySelector('img');if(!active||!image||!image.naturalWidth)return;const maxW=Math.max(1,stage.clientWidth-24),maxH=Math.max(1,stage.clientHeight-24),ratio=Math.min(1,maxW/image.naturalWidth,maxH/image.naturalHeight);active.baseWidth=image.naturalWidth*ratio;active.baseHeight=image.naturalHeight*ratio;setZoom(active.zoom);}
 function setZoom(z){if(!active||active.items[active.index].kind!=='image')return;const old=active.zoom||1;active.zoom=Math.min(5,Math.max(1,z));const image=surface.querySelector('img');const cx=stage.scrollLeft+stage.clientWidth/2,cy=stage.scrollTop+stage.clientHeight/2;if(image&&active.baseWidth){const width=active.baseWidth*active.zoom,height=active.baseHeight*active.zoom;image.style.width=width+'px';image.style.height=height+'px';surface.style.width=Math.max(stage.clientWidth,width+24)+'px';surface.style.height=Math.max(stage.clientHeight,height+24)+'px';}stage.classList.toggle('zoomed',active.zoom>1);stage.scrollLeft=cx*active.zoom/old-stage.clientWidth/2;stage.scrollTop=cy*active.zoom/old-stage.clientHeight/2;overlay.querySelector('#mediaZoom').textContent=Math.round(active.zoom*100)+'%';control('zoomOut').disabled=active.zoom<=1;control('zoomIn').disabled=active.zoom>=5;}
 function render(){
  if(!active)return;stopMedia();const item=active.items[active.index];active.zoom=1;active.baseWidth=0;active.baseHeight=0;surface.replaceChildren();surface.style.width=surface.style.height='';stage.scrollLeft=stage.scrollTop=0;stage.classList.remove('zoomed','dragging');
  const image=item.kind==='image',element=document.createElement(image?'img':'video');stage.style.touchAction=image?'pan-x pan-y':'auto';
  control('prev').disabled=active.index===0;control('next').disabled=active.index===active.items.length-1;for(const name of ['zoomOut','zoomIn','fit'])control(name).hidden=!image;overlay.querySelector('#mediaZoom').hidden=!image;
  overlay.querySelector('#mediaTitle').textContent=active.title;overlay.querySelector('#mediaCount').textContent=`${image?'现场图片':'动作视频'} ${item.number} · 素材 ${active.index+1} / ${active.items.length}`;
  [...strip.children].forEach((b,i)=>b.setAttribute('aria-current',String(i===active.index)));strip.children[active.index]?.scrollIntoView?.({block:'nearest',inline:'nearest'});
  status(image?'图片加载中…':'视频加载中… 点击播放；可使用全屏、进度和音量控制。');
  element.addEventListener('error',()=>{if(surface.firstChild===element)status(image?'图片无法加载，可能网络中断或场景已下架。':'视频无法播放，可能网络中断、场景已下架或编码不受浏览器支持。建议供应商上传 H.264 编码的 MP4。',true);});
  if(image){element.alt=active.title+' · 现场图片 '+item.number;element.draggable=false;element.onload=()=>{if(surface.firstChild!==element)return;fitSize();status('双击图片放大；也可使用 ＋ / −，放大后拖动查看。');};element.ondblclick=()=>setZoom(active.zoom>1?1:2);}
  else{element.controls=true;element.playsInline=true;element.preload='metadata';element.setAttribute('aria-label',active.title+' · 动作视频 '+item.number);element.addEventListener('loadedmetadata',()=>{if(surface.firstChild!==element)return;const saved=active.positions.get(item.url);if(saved&&Number.isFinite(element.duration)&&saved<element.duration)element.currentTime=saved;status('点击播放视频，点击“全屏观看”放大；关闭或切换会暂停播放。');});element.addEventListener('waiting',()=>status('视频缓冲中，请稍候…'));element.addEventListener('playing',()=>status('正在播放 · 支持进度拖动、音量与浏览器原生全屏'));}
  surface.append(element);element.src=item.url;if(image)setZoom(1);
 }
 function open(items,index,title,trigger){
  if(active)close();const blocked=[...document.body.children].filter(e=>e!==overlay&&!['SCRIPT','STYLE','LINK'].includes(e.tagName)).map(e=>({e,inert:e.inert,aria:e.getAttribute('aria-hidden')}));
  active={items,index,title,trigger,blocked,positions:new Map(),overflow:document.body.style.overflow,zoom:1};document.querySelectorAll('#modalContent video').forEach(v=>v.pause());for(const {e}of blocked){e.inert=true;e.setAttribute('aria-hidden','true');}document.body.style.overflow='hidden';overlay.hidden=false;strip.replaceChildren();items.forEach((item,i)=>{const b=document.createElement('button');b.type='button';b.textContent=(item.kind==='image'?'图片 ':'视频 ')+item.number;b.onclick=()=>move(i);strip.append(b);});render();control('close').focus();
 }
 function close(){if(!active)return;if(document.fullscreenElement&&overlay.contains(document.fullscreenElement))document.exitFullscreen?.().catch(()=>{});stopMedia();const previous=active;active=null;overlay.hidden=true;surface.replaceChildren();strip.replaceChildren();for(const {e,inert,aria}of previous.blocked){e.inert=inert;if(aria===null)e.removeAttribute('aria-hidden');else e.setAttribute('aria-hidden',aria);}document.body.style.overflow=previous.overflow;if(previous.trigger?.isConnected)previous.trigger.focus();}
 function move(index){if(!active||index<0||index>=active.items.length||index===active.index)return;stopMedia();active.index=index;render();}
 async function fullscreen(){if(!active)return;const video=surface.querySelector('video'),target=video||stage;try{if(document.fullscreenElement){await document.exitFullscreen();return;}if(target.requestFullscreen)await target.requestFullscreen();else if(video?.webkitEnterFullscreen){if(video.readyState<1){status('视频尚未就绪，请加载完成后再次点击“全屏观看”。');return;}video.webkitEnterFullscreen();}else status('当前浏览器不支持原生全屏，已使用大屏查看器；可旋转手机横屏观看。');}catch{status('全屏请求未成功，请再次点击；也可使用视频播放条中的全屏按钮。');}}
 overlay.addEventListener('click',e=>{const command=e.target.closest('[data-command]')?.dataset.command;if(!command||!active)return;if(command==='close')close();if(command==='prev')move(active.index-1);if(command==='next')move(active.index+1);if(command==='zoomIn')setZoom(active.zoom+.5);if(command==='zoomOut')setZoom(active.zoom-.5);if(command==='fit')setZoom(1);if(command==='fullscreen')fullscreen();});
 document.addEventListener('keydown',e=>{if(!active)return;if(e.key==='Escape'){if(document.fullscreenElement)return;e.preventDefault();e.stopImmediatePropagation();close();return;}if(e.key==='Tab'){const buttons=[...overlay.querySelectorAll('button,video')].filter(b=>!b.hidden&&!b.disabled&&(!b.closest('[hidden]')));const first=buttons[0],last=buttons.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}return;}if(e.target.tagName==='VIDEO'||document.fullscreenElement)return;if(['ArrowLeft','ArrowRight','+','=','-','0'].includes(e.key))e.preventDefault();if(e.key==='ArrowLeft')move(active.index-1);if(e.key==='ArrowRight')move(active.index+1);if(e.key==='+'||e.key==='=')setZoom(active.zoom+.5);if(e.key==='-')setZoom(active.zoom-.5);if(e.key==='0')setZoom(1);},true);
 let drag=null,touch=null,pinch=null;
 stage.addEventListener('pointerdown',e=>{if(active?.zoom>1&&e.pointerType==='mouse'&&e.button===0){drag={x:e.clientX,y:e.clientY,left:stage.scrollLeft,top:stage.scrollTop};stage.setPointerCapture(e.pointerId);stage.classList.add('dragging');e.preventDefault();}});
 stage.addEventListener('pointermove',e=>{if(drag){stage.scrollLeft=drag.left+drag.x-e.clientX;stage.scrollTop=drag.top+drag.y-e.clientY;}});for(const event of ['pointerup','pointercancel','lostpointercapture'])stage.addEventListener(event,()=>{drag=null;stage.classList.remove('dragging');});
 stage.addEventListener('wheel',e=>{if(active?.items[active.index].kind==='image'&&e.ctrlKey){e.preventDefault();setZoom(active.zoom+(e.deltaY<0?.25:-.25));}},{passive:false});
 const distance=t=>Math.hypot(t[0].clientX-t[1].clientX,t[0].clientY-t[1].clientY);
 stage.addEventListener('touchstart',e=>{if(!active||active.items[active.index].kind!=='image')return;if(e.touches.length===2){pinch={distance:distance(e.touches),zoom:active.zoom};touch=null;}else if(e.touches.length===1&&!pinch)touch={x:e.touches[0].clientX,y:e.touches[0].clientY};},{passive:true});
 stage.addEventListener('touchmove',e=>{if(pinch&&e.touches.length===2){e.preventDefault();setZoom(pinch.zoom*distance(e.touches)/Math.max(1,pinch.distance));}},{passive:false});
 stage.addEventListener('touchend',e=>{if(pinch){if(!e.touches.length)pinch=null;touch=null;return;}if(touch&&active?.zoom===1&&e.changedTouches.length){const dx=e.changedTouches[0].clientX-touch.x,dy=e.changedTouches[0].clientY-touch.y;if(Math.abs(dx)>60&&Math.abs(dx)>Math.abs(dy)*1.5)move(active.index+(dx<0?1:-1));}touch=null;});stage.addEventListener('touchcancel',()=>{touch=pinch=null;});
 window.addEventListener('resize',fitSize);window.addEventListener('pagehide',close);document.addEventListener('visibilitychange',()=>{if(document.hidden)surface.querySelector('video')?.pause();});
 function enhance(){document.querySelectorAll('#modalContent .gallery').forEach(gallery=>{const media=[...gallery.querySelectorAll('img,video')];let images=0,videos=0;const items=media.map(el=>({url:el.getAttribute('src'),kind:el.tagName==='IMG'?'image':'video',number:el.tagName==='IMG'?++images:++videos}));const title=document.querySelector('#modalContent h2')?.textContent||'场景素材';media.forEach((el,i)=>{if(el.closest('.media-card'))return;const button=document.createElement('button');button.type='button';button.className='media-card';button.setAttribute('aria-label',items[i].kind==='image'?`放大查看现场图片 ${items[i].number}`:`打开动作视频 ${items[i].number}，支持全屏播放`);const label=document.createElement('span');label.textContent=items[i].kind==='image'?`图片 ${items[i].number} · 点击查看大图 ↗`:`▶ 视频 ${items[i].number} · 大屏 / 全屏观看`;el.replaceWith(button);button.append(el,label);if(el.tagName==='IMG'){el.loading='lazy';el.alt=title+' · 图片 '+items[i].number;}else{el.controls=false;el.preload='metadata';el.muted=true;el.playsInline=true;el.tabIndex=-1;}el.addEventListener('error',()=>{label.textContent='素材加载失败 · 点击重试查看';});button.onclick=()=>open(items,i,title,button);});});}
 new MutationObserver(()=>{if(active&&!document.getElementById('modal').classList.contains('open'))close();enhance();}).observe(document.getElementById('modalContent'),{childList:true,subtree:true});
 new MutationObserver(()=>{if(active&&!document.getElementById('modal').classList.contains('open'))close();}).observe(document.getElementById('modal'),{attributes:true,attributeFilter:['class']});
 enhance();
})();
